#
# Master copy of dkms.conf for mpi3mr.
# Dont edit this file manually. Auto build script makes necessary changes.
#

PACKAGE_NAME="mpi3mr"
PACKAGE_VERSION="8.17.1.0.0-45d2"
BUILT_MODULE_NAME[0]="$PACKAGE_NAME"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
DEST_MODULE_LOCATION[0]="/updates"
REMAKE_INITRD="yes"
AUTOINSTALL="yes"
MODULES_CONF_ALIAS_TYPE[0]="scsi_hostadapter"
PATCH[0]=45drives.patch
