name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: buildinator-5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run test script
        run: ./test_builds.sh

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-build-logs
          path: |
            test_builds_out/**/*.log
          retention-days: 7
